#!/bin/bash
PSSAND="\"\[\033[38;5;118m\]\u\[$(tput sgr0)\]\[\033[38;5;124m\]@\h\[$(tput sgr0)\]\[\033[38;5;15m\]:\[$(tput sgr0)\]\[\033[38;5;6m\][\w]\[$(tput sgr0)\]\[\033[38;5;6m\]>\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]\""

if [ "$1" == "install" ]; then
  echo "Installing..."
  sudo apt-get update
  sudo apt-get install unionfs-fuse
  sudo cp $0 /usr/local/bin/$0
  echo "Installed!"
else
  tmprw=/tmp/rw #`mktemp -d`
  tmprt=/tmp/rt #`mktemp -d`
  sudo unionfs -o allow_other,cow,max_files=32000,use_ino,suid,dev,nonempty $tmprw=rw:/=ro $tmprt
  sudo mount -t proc proc $tmprt/proc
  sudo mount -t sysfs sys $tmprt/sys
  sudo mount --rbind /dev $tmprt/dev
  sudo mount --rbind /run $tmprt/run
  sudo grep -q -F "DISPLAY=${DISPLAY}" $tmprt/etc/environment || echo "DISPLAY=${DISPLAY}" | sudo tee --append $tmprt/etc/environment > /dev/null
  sudo grep -q -F "PS1=$PSSAND" $tmprt/etc/environment || echo "PS1=$PSSAND" | sudo tee --append $tmprt/etc/environment > /dev/null
  sudo chroot $tmprt env DISPLAY=:0 su - $USER
fi
